[proton]
install_dir = "~/.steam/root/compatibilitytools.d"
cache_dir = "/tmp/pup-rs"
repo = "proton-ge-custom"
owner = "GloriousEggroll"
symlink = "proton-ge-latest"

[lutris]
install_dir = "~/.local/share/lutris/runners/wine"
cache_dir = "/tmp/pup-rs"
repo = "wine-ge-custom"
owner = "GloriousEggroll"
symlink = "wine-ge-latest"